baseURL = "https://jinsoo-youn.github.io/blog"
languageCode = "en-us"
title = "Woody's Blog"
theme = "m10c"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Jinsoo Youn"
  description = "개인 블로그"
  #menu_item_separator = "/n"
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/jinsoo-youn"


