baseURL      = "https://jinsoo-youn.github.io/blog"
title        = "Woody's Blog"
languageCode = "ko-kr"
theme        = "papermod"

# ──────────────────────────────
# 메뉴
[[menu.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Posts"
  url    = "/posts/"
  weight = 2

# ──────────────────────────────
[params]                           # PaperMod 전용 파라미터
  author            = "Jinsoo Youn"
  description       = "개인 블로그"
  defaultTheme      = "auto"       # 다크/라이트 자동 전환
  ShowReadingTime   = true
  ShowCodeCopyButtons = true
