baseURL      = "https://jinsoo-youn.github.io/blog"
title        = "Woody's Blog"
languageCode = "ko-kr"
theme        = "papermod"

# ──────────────────────────────
# 메뉴
[[menu.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Posts"
  url    = "/posts/"
  weight = 2

# ──────────────────────────────
[params]                           # PaperMod 전용 파라미터
  author            = "Jinsoo Youn"
  description       = "개인 블로그"
  defaultTheme      = "auto"       # 다크/라이트 자동 전환
  ShowReadingTime   = true
  ShowCodeCopyButtons = true
  ShowToc = true         # 모든 포스트에서 TOC 표시
  TocOpen = true         # 기본 펼침 여부
  # 사용자 CSS 적용
  customCSS = ["css/extended/toc-right.css"]
